version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongoDB
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongovolume:/data/db

volumes:
  mongovolume:
    driver: local
